### ISSUE TITLE
404 on kernel download.

### ISSUE THREAD

**Issue by airyy** [leifliddy/macbook12-bluetooth-driver#1]
First off, thank you for starting this repo. Definitely needed.

Those with kernel 5.0.0 will get a 404 error because on line 3 it sets the kernel version as 5.0.0 but there is no 5.0.0 download, only 5.0. I would do a pull request but my bash skills are not the greatest.

Thanks

**Comment by leifliddy** [comment]
The script will first try to download version 5.x.x.x, and if that fails it will attempt to download version 5.x.x


```
if [[ $? -ne 0 ]]; then
   # if first attempt fails, attempt to download linux-x.x.tar.xz kernel
   kernel_version=$major_version.$minor_version
   wget -c https://cdn.kernel.org/pub/linux/kernel/v$major_version.x/linux-$kernel_version.tar.xz -P $build_dir
fi
```

So, if your output of ```uname -r``` was 5.0.0-100.something.x86_64, the the script would first try to 
download kernel 
```https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.0.tar.xz```
and if that failed, it would attempt to download:
```https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.0.tar.xz```



In fact, I just manully set ```kernel-version``` to 5.0.0. And this was the resulting output:

```
--2019-12-25 12:14:47--  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.0.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 2a04:4e42::432, 2a04:4e42:200::432, 2a04:4e42:400::432, ...
Connecting to cdn.kernel.org (cdn.kernel.org)|2a04:4e42::432|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-25 12:14:48 ERROR 404: Not Found.

--2019-12-25 12:14:48--  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 2a04:4e42::432, 2a04:4e42:200::432, 2a04:4e42:400::432, ...
Connecting to cdn.kernel.org (cdn.kernel.org)|2a04:4e42::432|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105235152 (100M) [application/x-xz]
Saving to: ‘build/linux-5.0.tar.xz’

linux-5.0.tar.xz                              100%[===============================================================================================>] 100.36M   149MB/s    in 0.7s    

2019-12-25 12:14:49 (149 MB/s) - ‘build/linux-5.0.tar.xz’ saved [105235152/105235152]
```

Please send me the following:
1. the output of ```uname -r```
2. the output that's displayed to screen when running ```install.bluetooth.sh```

**Comment by airyy** [comment]
Current kernel version is: 5.0.0-37-generic. I did see that line but it does not seem to be working properly as I still get 404's and the script just exits.

sh install.bluetooth.sh 
install.bluetooth.sh: 8: install.bluetooth.sh: [[: not found
install.bluetooth.sh: 14: install.bluetooth.sh: [[: not found
install.bluetooth.sh: 15: install.bluetooth.sh: [[: not found
--2019-12-25 13:34:42--  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.0.0.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 151.101.113.176, 2a04:4e42:1b::432
Connecting to cdn.kernel.org (cdn.kernel.org)|151.101.113.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-25 13:34:45 ERROR 404: Not Found.

**Comment by leifliddy** [comment]
Please look at the README file I've recently created
https://github.com/leifliddy/macbook12-bluetooth-driver/blob/master/README.md

It clearly shows you how to run the script.
```./bluetooth.install.sh```

...but you can also run in it using the ```bash``` command interpreter
ie
```bash bluetooth.install.sh```

**Comment by leifliddy** [comment]
```sh``` should work as long as it's linked to ```bash```
what is the output of?
```ls -la $(which sh)```
