### ISSUE TITLE
Bluetooth: hci0: BCM: firmware Patch file not found

### ISSUE THREAD

**Issue by mfauvain** [leifliddy/macbook12-bluetooth-driver#10]
Bluetooth works with the patch however log has :
`Bluetooth: hci0: BCM: firmware Patch file not found, tried:`
`Bluetooth: hci0: BCM: 'brcm/BCM.hcd'`

Am I missing a part? or is this normal?

**Comment by leifliddy** [comment]
Yes, that's normal. This bluetooth controller doesn't require any firmware. It's controlled via ACPI methods:
https://github.com/Dunedan/mbp-2016-linux/issues/29#issuecomment-320493265
