### ISSUE TITLE
macbook 9,1 mint 20, still nothing seen

### ISSUE THREAD

**Issue by ironhands79** [leifliddy/macbook12-bluetooth-driver#17]
i can see the file compiled and is in the updates folder, but i'm still seeing nothing in bluetoothctl - scan, i'm seeing:

`ferrus@0x10000078:~/macbook12-audio-driver$` lsusb; dmesg | egrep -i blue|firm
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[    0.115895] Spectre V2 : Enabling Restricted Speculation for firmware calls
[    0.142599] ACPI: [Firmware Bug]: BIOS _OSI(Linux) query ignored
[    1.168575] [drm] Finished loading DMC firmware i915/skl_dmc_ver1_27.bin (v1.27)
[    6.297939] Bluetooth: Core ver 2.22
[    6.297980] Bluetooth: HCI device and connection manager initialized
[    6.297986] Bluetooth: HCI socket layer initialized
[    6.297988] Bluetooth: L2CAP socket layer initialized
[    6.297992] Bluetooth: SCO socket layer initialized
[    6.394450] Bluetooth: HCI UART driver ver 2.3
[    6.394452] Bluetooth: HCI UART protocol H4 registered
[    6.394453] Bluetooth: HCI UART protocol BCSP registered
[    6.394475] Bluetooth: HCI UART protocol LL registered
[    6.394476] Bluetooth: HCI UART protocol ATH3K registered
[    6.394489] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    6.394536] Bluetooth: HCI UART protocol Intel registered
[    6.394656] Bluetooth: HCI UART protocol Broadcom registered
[    6.394666] Bluetooth: HCI UART protocol QCA registered
[    6.394667] Bluetooth: HCI UART protocol AG6XX registered
[    6.394677] Bluetooth: HCI UART protocol Marvell registered
[    6.506879] brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.Apple Inc.-MacBook9,1.txt failed with error -2
[    6.506904] brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.txt failed with error -2
[    6.792977] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4350/5 wl0: Nov 26 2015 03:48:57 version 7.35.180.133 (r602372) FWID 01-c45b39d6
[    7.141960] Bluetooth: hci0: BCM: failed to write update baudrate (-16)
[    7.141964] Bluetooth: hci0: Failed to set baudrate
[    7.252748] Bluetooth: hci0: BCM: chip id 92
[    7.254258] Bluetooth: hci0: BCM: features 0x2f
[    7.256097] Bluetooth: hci0: BCM4350C0 UART 37.4 MHz Gamay Murata UHE
[    7.256100] Bluetooth: hci0: BCM (003.001.107) build 1423
[    8.020639] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    8.020642] Bluetooth: BNEP filters: protocol multicast
[    8.020646] Bluetooth: BNEP socket layer initialized
[    9.359964] Bluetooth: hci0: command 0xfc4c tx timeout
[   17.488011] Bluetooth: hci0: BCM: Patch command fc4c failed (-110)
[   17.488022] Bluetooth: hci0: BCM: Patch failed (-110)
[   19.504150] Bluetooth: hci0: command 0x0c03 tx timeout
[   27.728158] Bluetooth: hci0: BCM: Reset failed (-110)
`
Any ideas?  I think this is the same machine you were using when all this began, one single usb-c port doesn't cut it 8p

**Comment by leifliddy** [comment]
did you reboot the machine after running the install script?

**Comment by ironhands79** [comment]
yes, quite curious.

**Comment by ironhands79** [comment]
yes, quite curious.  installed the 5.13 kernel, reinstalled the script, no change

**Comment by leifliddy** [comment]
you're still getting these errors?
```
Bluetooth: hci0: command 0x0c03 tx timeout
Bluetooth: hci0: BCM: Reset failed (-110)
```

**Comment by ironhands79** [comment]
correct, i have run the script a second time with a fresh git clone, no errors, and a restart, still seeing timeouts/fails setting baud rate and resetting

**Comment by ironhands79** [comment]
noticed a slight difference:

```
[    6.350491] Bluetooth: HCI UART protocol Marvell registered
[    6.890750] brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.Apple Inc.-MacBook9,1.txt failed with error -2
[    6.890794] brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.txt failed with error -2
[    7.102618] Bluetooth: hci0: BCM: failed to write update baudrate (-16)
[    7.102628] Bluetooth: hci0: Failed to set baudrate
[    7.182291] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4350/5 wl0: Nov 26 2015 03:48:57 version 7.35.180.133 (r602372) FWID 01-c45b39d6
[    7.210392] Bluetooth: hci0: BCM: chip id 92
[    7.210689] Bluetooth: hci0: BCM: features 0x2f
[    7.211846] Bluetooth: hci0: BCM4350C0 UART 37.4 MHz Gamay Murata UHE
[    7.211852] Bluetooth: hci0: BCM (003.001.107) build 1423
[    **7.212852] Bluetooth: hci0: BCM 'brcm/BCM.hcd' Patch**
[    7.535664] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    7.535668] Bluetooth: BNEP filters: protocol multicast
[    7.535673] Bluetooth: BNEP socket layer initialized
[    9.309555] Bluetooth: hci0: command 0xfc4c tx timeout
[   17.469560] Bluetooth: hci0: BCM: Patch command fc4c failed (-110)
[   17.469570] Bluetooth: hci0: BCM: Patch failed (-110)
[   19.489578] Bluetooth: hci0: command 0xfc18 tx timeout
[   27.709577] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   29.729585] Bluetooth: hci0: command 0x0c03 tx timeout
[   37.949749] Bluetooth: hci0: BCM: Reset failed (-110)
```

hci0: BCM 'brcm/BCM.hcd' 
wasn't there before

**Comment by leifliddy** [comment]
the error that really matters is 
```
[   29.729585] Bluetooth: hci0: command 0x0c03 tx timeout
[   37.949749] Bluetooth: hci0: BCM: Reset failed (-110)
```
There is no firmware on this bluetooth controller, so those other errors are harmless.

**Comment by leifliddy** [comment]
weird, I've never seen this before 
```[    9.309555] Bluetooth: hci0: command 0xfc4c tx timeout
[   17.469560] Bluetooth: hci0: BCM: Patch command fc4c failed (-110)
```

could you post the output of 
```ll /lib/modules/$(uname -r)/updates/hci_uart.ko```

and
```rfkill```

**Comment by ironhands79** [comment]
`-rw-r--r-- 1 root root 265248 Jan  5 15:52 /lib/modules/5.13.0-23-generic/updates/hci_uart.ko
`
```
ID TYPE      DEVICE      SOFT      HARD
 0 bluetooth hci0   unblocked unblocked
 1 wlan      phy0   unblocked unblocked
```

**Comment by leifliddy** [comment]
nevermind, I see that error here:
https://github.com/leifliddy/macbook12-bluetooth-driver/issues/9

could you post the output of 
```lsmod | egrep 'bt|blue'```

and 

``` systemctl status bluetooth.service```

**Comment by ironhands79** [comment]
```
btqca                  24576  1 hci_uart
btrtl                  24576  1 hci_uart
btbcm                  16384  1 hci_uart
btintel                32768  1 hci_uart
bluetooth             651264  13 btrtl,btqca,btintel,hci_uart,btbcm,bnep
ecdh_generic           16384  1 bluetooth
btrfs                1388544  0
xor                    24576  1 btrfs
zstd_compress         176128  1 btrfs
raid6_pq              114688  1 btrfs
libcrc32c              16384  1 btrfs
```
```

 bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-01-05 15:55:29 EST; 49min ago
       Docs: man:bluetoothd(8)
   Main PID: 688 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 9288)
     Memory: 1.5M
     CGroup: /system.slice/bluetooth.service
             └─688 /usr/lib/bluetooth/bluetoothd

Jan 05 15:55:29 0x10000078 systemd[1]: Starting Bluetooth service...
Jan 05 15:55:29 0x10000078 bluetoothd[688]: Bluetooth daemon 5.53
Jan 05 15:55:29 0x10000078 systemd[1]: Started Bluetooth service.
Jan 05 15:55:29 0x10000078 bluetoothd[688]: Starting SDP server
Jan 05 15:55:29 0x10000078 bluetoothd[688]: Bluetooth management interface 1.20 initialized


```

**Comment by ironhands79** [comment]
so it appears that its still attempting to load bcm.hcd when its not needed?

**Comment by leifliddy** [comment]
It always attempts to do that, here are the logs on my system 
```
[root@mac ~]# journalctl -b | egrep -i 'bluetooth|brcm' | head -40
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: Core ver 2.22
Jan 01 12:24:20 mac.example.com kernel: NET: Registered PF_BLUETOOTH protocol family
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI device and connection manager initialized
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI socket layer initialized
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: L2CAP socket layer initialized
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: SCO socket layer initialized
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART driver ver 2.3
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol H4 registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol BCSP registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol LL registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol ATH3K registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol Three-wire (H5) registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol Intel registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol Broadcom registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol QCA registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol AG6XX registered
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: HCI UART protocol Marvell registered
Jan 01 12:24:20 mac.example.com kernel: usbcore: registered new interface driver brcmfmac
Jan 01 12:24:20 mac.example.com kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4350c2-pcie for chip BCM4350/5
Jan 01 12:24:20 mac.example.com kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.Apple Inc.-MacBook9,1.bin failed with error -2
Jan 01 12:24:20 mac.example.com kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.Apple Inc.-MacBook9,1.txt failed with error -2
Jan 01 12:24:20 mac.example.com kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4350c2-pcie.txt failed with error -2
Jan 01 12:24:20 mac.example.com kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4350c2-pcie for chip BCM4350/5
Jan 01 12:24:20 mac.example.com kernel: brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
Jan 01 12:24:20 mac.example.com kernel: brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4350/5 wl0: Nov 26 2015 03:48:57 version 7.35.180.133 (r602372) FWID 01-c45b39d6
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: hci0: BCM: failed to write update baudrate (-16)
Jan 01 12:24:20 mac.example.com kernel: Bluetooth: hci0: Failed to set baudrate
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM: chip id 92
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM: features 0x2f
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM4350C0 UART 37.4 MHz Gamay USI UHE
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM (003.001.134) build 1532
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM: firmware Patch file not found, tried:
Jan 01 12:24:21 mac.example.com kernel: Bluetooth: hci0: BCM: 'brcm/BCM.hcd'
Jan 01 12:24:21 mac.example.com kernel: brcmfmac 0000:02:00.0 wlp2s0: renamed from wlan0
Jan 01 12:24:21 mac.example.com systemd[1]: Starting Bluetooth service...
Jan 01 12:24:21 mac.example.com bluetoothd[1214]: Bluetooth daemon 5.62
Jan 01 12:24:21 mac.example.com audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 01 12:24:21 mac.example.com systemd[1]: Started Bluetooth service.
Jan 01 12:24:21 mac.example.com systemd[1]: Reached target Bluetooth Support.
Jan 01 12:24:21 mac.example.com bluetoothd[1214]: Starting SDP server
```

I'm not sure why you're getting those timeouts though. I might have some time later in the week to troubleshoot it further, just really busy ATM.

**Comment by ironhands79** [comment]
oh no problems at all, really appreciate the effort you've put into this.  got my sounds working and that was more than i had expected.  have a great night, thanks again!!

**Comment by leifliddy** [comment]
```
[root@mac ~]# bluetoothctl 
Agent registered
[CHG] Controller F4:0F:24:02:8C:70 Pairable: yes
[bluetooth]# list
Controller F4:0F:24:02:8C:70 mac.example.com [default]
```

**Comment by ironhands79** [comment]
Did a reinstall first thing this morning, no updates. Changed the kernel to 5.14.0.23-generic. worked immediately. Rebooted to add the sound driver, perfect. Ran some updates and no issue yet. Didn't update bluez, maybe it was causing an issue, but it's working now so I'll leave it alone.

Again thanks so much for your time and effort on the project!
