### ISSUE TITLE
Error when compiling hci_bcm.c

### ISSUE THREAD

**Issue by airyy** [leifliddy/macbook12-bluetooth-driver#2]
After manually setting the version, it was able to download the correct kernel. However, upon running script again, it gets an error when trying to compile hci_bcm.c

error: implicit declaration of function ‘hci_uart_has_flow_control’; did you mean ‘hci_uart_set_flow_control’? [-Werror=implicit-function-declaration]

Thanks

**Comment by leifliddy** [comment]
I've just modified ```install.bluetooth.sh```
It will now auto-patch ```hci_hcm.c``` for any kernel version. 
Try running it now.

**Comment by leifliddy** [comment]
Also, do you have your kernel development libraries installed?
ie
for Fedora
```
dnf install kernel-devel
```
for Ubuntu
```
apt install linux-headers-generic
```
I'll make a readme file in the next few days....

**Comment by leifliddy** [comment]
Which Linux distro/version are you running?
Are you running a custom or stock kernel ?

**Comment by airyy** [comment]
Hey, thanks for changing. I will try updated in a few minutes. I did not have the headers package installed but I just installed it. I am running stock Ubuntu 18.04 with stock kernel 5.0.0-37

Thanks

**Comment by airyy** [comment]
So it ran what looks like successfully, last part of output is:

  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/l/macbook12-bluetooth-driver/build/bluetooth-5.0/hci_uart.mod.o
  LD [M]  /home/l/macbook12-bluetooth-driver/build/bluetooth-5.0/hci_uart.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-37-generic'
xz hci_uart.ko
cp hci_uart.ko.xz /lib/modules/5.0.0-37-generic/updates
depmod -a
-e 
contents of /lib/modules/5.0.0-37-generic/updates
total 48
drwxr-xr-x 2 root root  4096 Dec 24 15:12 dkms
-rw-r--r-- 1 root root 42772 Dec 25 14:04 hci_uart.ko.xz

However, I rebooted and still no bluetooth connectivity, did I do something wrong or just does not work for me?

Thanks

**Comment by airyy** [comment]
When I extracted the .ko file and tried to update myself by running: sudo depmod hci_uart.ko
I got the error:
depmod: ERROR: Bad version passed hci_uart.ko

**Comment by leifliddy** [comment]
compressing the module is just a preference, it should work either way. Fedora xz compresses modules by default, so what I've gone with.

You can easily change that behavior be modifying the ```Makefile``` and changing:
```
install:
	xz hci_uart.ko
	cp hci_uart.ko.xz /lib/modules/$(shell uname -r)/updates
```
to
```
install:
	cp hci_uart.ko /lib/modules/$(shell uname -r)/updates
```

**Comment by leifliddy** [comment]
I've just modified the ```Makefile``` and removed the xz compression command. 
I'm not 100% sure if xz compressed modules are compatible with Ubuntu or not.
Do a ```git pull``` and try running it now.

**Comment by leifliddy** [comment]
Which macbook model do you have?

**Comment by leifliddy** [comment]
If you're still experiencing bluetooth issues, send me your:
1. ```dmesg``` output
2. ```lsmod``` output

**Comment by airyy** [comment]
Alright, just reinstalled Ubuntu 18.04 and downloaded your script fresh and although it runs smooth, it does not fix the Bluetooth. Below you will find the outputs of the commands you asked me to run, am only selecting Bluetooth to grep but if you want all, I can do that to:

1.
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   14.299835] Bluetooth: BNEP filters: protocol multicast
[   14.299837] Bluetooth: BNEP socket layer initialized
[   16.208495] Bluetooth: hci0: command 0xfc18 tx timeout
[   17.629613] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
[   24.368542] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   24.368547] Bluetooth: hci0: Failed to set baudrate
[   25.040852] broken atomic modeset userspace detected, disabling atomic
[   26.384542] Bluetooth: hci0: command 0x0c03 tx timeout
[   27.557871] rfkill: input handler disabled
[   34.608474] Bluetooth: hci0: BCM: Reset failed (-110)

2.
bluetooth             557056  13 btrtl,btqca,btintel,hci_uart,btbcm,bnep

3.
https://paste.ee/p/4Z6FX#dyG1OOfoO85FMyNouFhxUmRd2912kdiA

**Comment by leifliddy** [comment]
What Macbook model do you have?
And yes, I need you to post your entire dmesg log.

**Comment by leifliddy** [comment]
Also, please post the output of
```lsinitramfs /boot/initrd.img-$(uname -r) | egrep 'bluetooth|btrtl|btbcm|btintel|uart'```

**Comment by leifliddy** [comment]
BTW, you don't need to reinstall Ubuntu  --we're not dealing w/ windows here ; )
Any issue we come across can be identified and solved. 
I'll give you an explanation about how kernel modules work --once we work out this issue.

**Comment by leifliddy** [comment]
Also, I identified the issue you're experiencing. For kernels 5.0 and 5.1, you'll need to apply this patch:
https://lkml.org/lkml/2019/3/31/344

I'll modify ```install.bluetooth.sh``` later to incorporate this patch.

**Comment by leifliddy** [comment]
Also, the next time you create an issue, be sure to list the details of your system.
ie
Ubuntu 18.04
Kernel 5.0
Macbook9,1 (12 inch) 

Starting off an issue with just 'hey this thing doesn't work' isn't enough info.
Many driver issues are kernel-specific and/or hardware-specific. It also helps to know what Linux os/version you're running as each Linux distro has different kernel, initramfs, package...etc configurations.

**Comment by airyy** [comment]
Alright, sorry have not been active much on Github until I came across this set of issues. I have the MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports).

dmesg - https://paste.ee/p/S5Ptt#hbuclXAWXHagmblJUOT5Lx2gKOz6h40e
lsmod - https://paste.ee/p/RqD1V#cwTVnop9brTT5rg8pfSUfeP3JNpJphvQ
lsinitramfs - https://paste.ee/p/s7l0C#66c0SHDQ7H6psWztBKaFKiVMQ3Loy394

And yeah, going forward when opening issues will give system specs. Thanks again for your help.

**Comment by leifliddy** [comment]
No worries, I'll have the fix implemented for you later today. 
Also, the model identifier is what's normally used to identify Macbooks.  
Based on your description, I think you have a MacBookPro14,1

**Comment by leifliddy** [comment]
Ok, I've just added support for kernels 5.0 and 5.1.
Can you try out the new version?

**Comment by airyy** [comment]
Yeah that's what I think I have as well. I just re-downloaded and ran patch and it still does not work. Let me know if you think resetting completely will help.

Thanks

**Comment by leifliddy** [comment]
can you ```cd``` to ```/home/l/macbook12-bluetooth-driver/build/bluetooth-5.0```
and send me the output of:
```diff -up hci_bcm.c.orig hci_bcm.c```

**Comment by airyy** [comment]
https://paste.ee/p/Kkzip#p32RcudFXmmpylsbk4b5x7JU6ADTTEgH

**Comment by leifliddy** [comment]
That's not right. It should look like this:
```
--- hci_bcm.c.orig	2019-03-04 00:21:29.000000000 +0100
+++ hci_bcm.c	2019-12-26 16:00:13.608215041 +0100
@@ -228,9 +228,15 @@ static int bcm_gpio_set_power(struct bcm
 	int err;
 
 	if (powered && !dev->res_enabled) {
-		err = regulator_bulk_enable(BCM_NUM_SUPPLIES, dev->supplies);
-		if (err)
-			return err;
+		/* Intel Macs use bcm_apple_get_resources() and don't
+		 * have regulator supplies configured.
+		 */
+		if (dev->supplies[0].supply) {
+			err = regulator_bulk_enable(BCM_NUM_SUPPLIES,
+						    dev->supplies);
+			if (err)
+				return err;
+		}
 
 		/* LPO clock needs to be 32.768 kHz */
 		err = clk_set_rate(dev->lpo_clk, 32768);
@@ -252,14 +258,16 @@ static int bcm_gpio_set_power(struct bcm
 	if (err)
 		goto err_txco_clk_disable;
 
-	err = dev->set_device_wakeup(dev, powered);
-	if (err)
-		goto err_revert_shutdown;
-
 	if (!powered && dev->res_enabled) {
 		clk_disable_unprepare(dev->txco_clk);
 		clk_disable_unprepare(dev->lpo_clk);
-		regulator_bulk_disable(BCM_NUM_SUPPLIES, dev->supplies);
+
+		/* Intel Macs use bcm_apple_get_resources() and don't
+		 * have regulator supplies configured.
+		 */
+		if (dev->supplies[0].supply)
+			regulator_bulk_disable(BCM_NUM_SUPPLIES,
+					       dev->supplies);
 	}
 
 	/* wait for device to power on and come out of reset */
@@ -269,8 +277,6 @@ static int bcm_gpio_set_power(struct bcm
 
 	return 0;
 
-err_revert_shutdown:
-	dev->set_shutdown(dev, !powered);
 err_txco_clk_disable:
 	if (powered && !dev->res_enabled)
 		clk_disable_unprepare(dev->txco_clk);
```
Did you modify ```install.bluetooth.sh``` at all?

**Comment by leifliddy** [comment]
This line looks at the value of ```$kernel_short_version```. If the value is 5.0 or 5.1, it should copy over the ```hci_bcm.kernel_5.0_5.1.c``` file

```
[[ $(echo "$kernel_short_version" | grep '5.[0-1]') ]] && cp $patch_dir/hci_bcm.kernel_5.0_5.1.c $bluetooth_dir/hci_bcm.c
```

**Comment by leifliddy** [comment]
can you add this echo statement to ```install.bluetooth.sh```
```
kernel_short_version="$major_version.$minor_version" #ie 5.2
echo "kernel_short_version is $kernel_short_version"
```

**Comment by airyy** [comment]
I changed line 3 to 5.0 because of the first issue I opened. I see the script is supposed to download 5.0 on its own but it didn't so I just manually set the variable.

Output is kernel_short_version is .

I think Ubuntu has an issue parsing lines with [[ because script gives errors:
https://paste.ee/p/WuIGw#Cr63qgPQ54foDa9P5e6zg6pCZZIxBynw

**Comment by leifliddy** [comment]
Leave the script as is, you don't need modify it. If you modify it, don't ask me to support it.
Look at my last two comments here:
https://github.com/leifliddy/macbook12-bluetooth-driver/issues/1

Please read the instructions in the readme.md file. I NEVER stated to run the script with ```sh```
The instructions are there for a reason.

**Comment by leifliddy** [comment]
My guess is --is that if you run
```ls -la /bin/sh```
...that it's not linked to ```/bin/bash``` which would explain the symptoms of the issue you're experiencing.

**Comment by airyy** [comment]
Well, running with ./ as stated in the readme does not work so I was told to run with sh prefix when researching.

The output of that command is: lrwxrwxrwx 1 root root 4 Dec 25 18:18 /bin/sh -> dash

How else was I supposed to even realize these errors if the script just 404's, I had to modify it to get it to run through. This is a fresh install of Ubuntu so maybe ./ works great with Fedora but not here, not sure.

**Comment by leifliddy** [comment]
so ```dash``` is not ```bash``` it won't interpret the script the same way. 
The script is meant to be run as root, but you can obviously prefix the command with ```sudo```

Just ran this script on an ubuntu 18.04 system. 
```
root@miner:/tmp/macbook12-bluetooth-driver# ./install.bluetooth.sh 
--2019-12-27 01:09:00--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.15.0.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 151.101.1.176, 151.101.65.176, 151.101.129.176, ...
Connecting to cdn.kernel.org (cdn.kernel.org)|151.101.1.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-27 01:09:02 ERROR 404: Not Found.

--2019-12-27 01:09:02--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.15.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 151.101.193.176, 151.101.129.176, 151.101.65.176, ...
Connecting to cdn.kernel.org (cdn.kernel.org)|151.101.193.176|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 102181404 (97M), 101714507 (97M) remaining [application/x-xz]
Saving to: ‘build/linux-4.15.tar.xz’

linux-4.15.tar.xz                   100%[=================================================================>]  97.45M  2.75MB/s    in 37s     

2019-12-27 01:09:39 (2.65 MB/s) - ‘build/linux-4.15.tar.xz’ saved [102181404/102181404]

tar --strip-components=2 -xvf build/linux-4.15.tar.xz linux-4.15/drivers/bluetooth --directory=build/
linux-4.15/drivers/bluetooth/
linux-4.15/drivers/bluetooth/Kconfig
linux-4.15/drivers/bluetooth/Makefile
linux-4.15/drivers/bluetooth/ath3k.c
linux-4.15/drivers/bluetooth/bcm203x.c
linux-4.15/drivers/bluetooth/bfusb.c
linux-4.15/drivers/bluetooth/bluecard_cs.c
linux-4.15/drivers/bluetooth/bpa10x.c
linux-4.15/drivers/bluetooth/bt3c_cs.c
linux-4.15/drivers/bluetooth/btbcm.c
linux-4.15/drivers/bluetooth/btbcm.h
linux-4.15/drivers/bluetooth/btintel.c
linux-4.15/drivers/bluetooth/btintel.h
linux-4.15/drivers/bluetooth/btmrvl_debugfs.c
linux-4.15/drivers/bluetooth/btmrvl_drv.h
linux-4.15/drivers/bluetooth/btmrvl_main.c
linux-4.15/drivers/bluetooth/btmrvl_sdio.c
linux-4.15/drivers/bluetooth/btmrvl_sdio.h
linux-4.15/drivers/bluetooth/btqca.c
linux-4.15/drivers/bluetooth/btqca.h
linux-4.15/drivers/bluetooth/btqcomsmd.c
linux-4.15/drivers/bluetooth/btrtl.c
linux-4.15/drivers/bluetooth/btrtl.h
linux-4.15/drivers/bluetooth/btsdio.c
linux-4.15/drivers/bluetooth/btuart_cs.c
linux-4.15/drivers/bluetooth/btusb.c
linux-4.15/drivers/bluetooth/btwilink.c
linux-4.15/drivers/bluetooth/dtl1_cs.c
linux-4.15/drivers/bluetooth/hci_ag6xx.c
linux-4.15/drivers/bluetooth/hci_ath.c
linux-4.15/drivers/bluetooth/hci_bcm.c
linux-4.15/drivers/bluetooth/hci_bcsp.c
linux-4.15/drivers/bluetooth/hci_h4.c
linux-4.15/drivers/bluetooth/hci_h5.c
linux-4.15/drivers/bluetooth/hci_intel.c
linux-4.15/drivers/bluetooth/hci_ldisc.c
linux-4.15/drivers/bluetooth/hci_ll.c
linux-4.15/drivers/bluetooth/hci_mrvl.c
linux-4.15/drivers/bluetooth/hci_nokia.c
linux-4.15/drivers/bluetooth/hci_qca.c
linux-4.15/drivers/bluetooth/hci_serdev.c
linux-4.15/drivers/bluetooth/hci_uart.h
linux-4.15/drivers/bluetooth/hci_vhci.c
make -C /lib/modules/4.15.0-39-generic/build M=/tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0 modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-39-generic'
Makefile:975: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_ldisc.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_serdev.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_h4.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_bcsp.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_ll.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_ath.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_h5.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_intel.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_bcm.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_qca.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_ag6xx.o
  CC [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_mrvl.o
  LD [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_uart.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_uart.mod.o
  LD [M]  /tmp/macbook12-bluetooth-driver/build/bluetooth-4.15.0/hci_uart.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-39-generic'
cp hci_uart.ko /lib/modules/4.15.0-39-generic/updates
depmod -a

contents of /lib/modules/4.15.0-39-generic/updates
total 200
drwxr-xr-x 1 root root    102 Sep  3 00:51 dkms
-rw-r--r-- 1 root root 202512 Dec 27 01:09 hci_uart.ko
```

**Comment by leifliddy** [comment]
can you show me the output when you run the script with ```./install.bluetooth.sh```?

**Comment by leifliddy** [comment]
the first line of the ```install.bluetooth.sh``` is 
```#!/bin/bash```
which means it requires the ```bash``` command interpreter to run, not ```dash```. Not every ```bash``` construct will be supported by ```dash```

**Comment by leifliddy** [comment]
when running a script with ```./``` the it will use the command interpreter listed in the first line of the file.
when running script with the command interpreter ie 
```dash script.sh```
```bash script.sh``` 
...then the first line of the file ie ```#!/bin/bash``` is irrelevant, as you're specifying the command interpreter.

ie
if you run a script as ```dash script.sh```, you're forcing that script to run as a dash script.

**Comment by airyy** [comment]
I think what made me use sh directly was because in readme, it gave an invalid filename which gave an error so I tried with sh and then used tab to get the filename so I continued to use that instead of ./install-bluetooth.sh I understand now that this will not use the right interpreter.

./ - https://paste.ee/p/RV08W#aLgQDdfGPHKftEaREpVENM5KOwP23orn
sudo ./ - https://paste.ee/p/0SYgM#tOuFa9hXi2C1Tpro5tHNleIgHnJHVRLX
bash - https://paste.ee/p/3diBA#bompz4uohFll715eTCwPMc0d32A6b9fb
sudo bash - https://paste.ee/p/ZPrGa#5KNaSZHF8ZiPrf9h6PXkuSBaW9DsO3nw

Thanks

**Comment by leifliddy** [comment]
As I stated before, if you the script without ```sudo``` , it needs to be run as ```root```
as normal user, you change to the root user using a number of methods
ie
```su -```
```sudo bash```
...otherwise you'll get those permission errors. 
Use whatever method suits you. If you like using ```sudo``` then use ```sudo```
....anyways, is bluetooth working for you now?

**Comment by airyy** [comment]
Yeah, when I get permission errors I just use sudo. I just rebooted and Bluetooth still does not work, should I reset?

**Comment by leifliddy** [comment]
can you run that ```diff``` command again?
```diff -up hci_bcm.c.orig hci_bcm.c```

**Comment by airyy** [comment]
https://paste.ee/p/s7quA#Ht2NnnU9FsWQznp8JgA18vHbXs9dasTr

**Comment by leifliddy** [comment]
Ok, that looks good! Can post your ```dmesg``` log?

**Comment by airyy** [comment]
https://paste.ee/p/XzhJ3#BBEJJqAnFDq5iRL7BXNq5qaGL7Vvzp40

**Comment by leifliddy** [comment]
can you post the output of 
```ls -la /lib/modules/4.15.0-39-generic/updates```

**Comment by airyy** [comment]
ls: cannot access '/lib/modules/4.15.0-39-generic/update': No such file or directory

When I run uname-r I get: 5.0.0-37-generic, so I did: ls -la /lib/modules/5.0.0-37-generic/updates and got: -rw-r--r-- 1 root root 229160 Dec 26 16:34 /lib/modules/5.0.0-37-generic/updates

**Comment by leifliddy** [comment]
sorry, I'm an idiot ; )
ok, try this:
```sudo ls -la /lib/modules/5.0.0-37-generic/updates```

**Comment by leifliddy** [comment]
wait....there's no files in ```/lib/modules/5.0.0-37-generic/updates```?

**Comment by airyy** [comment]
Yeah, same output: -rw-r--r-- 1 root root 229160 Dec 26 16:34 /lib/modules/5.0.0-37-generic/updates

**Comment by leifliddy** [comment]
that's odd....what's the output of ```ls -ltr /lib/modules```

**Comment by airyy** [comment]
total 12
drwxr-xr-x 5 root root 4096 Aug  5 14:05 5.0.0-23-generic
drwxr-xr-x 2 root root 4096 Dec 25 18:58 4.15.0-72-generic
drwxr-xr-x 5 root root 4096 Dec 26 17:03 5.0.0-37-generic

**Comment by leifliddy** [comment]
ahhh....I think I see the the issue
for some reason ```/lib/modules/5.0.0-37-generic/updates``` is a file....not a directory
ok do this:
```sudo rm -rf  /lib/modules/5.0.0-37-generic/updates```
```sudo mkdir /lib/modules/5.0.0-37-generic/updates```
```sudo bash install.bluetooth.sh```

**Comment by leifliddy** [comment]
**I just modified the ```install.bluetooth.sh``` script to create the /lib/modules/$(uname -r)/updates if it doesn't exist.

**Comment by airyy** [comment]
Done, it is fixed. Thank you so much for the help and continued support on fixing this.

**Comment by leifliddy** [comment]
bluetooth is working!?

**Comment by airyy** [comment]
Yes haha, rebooted and all is good. Thanks so much

**Comment by leifliddy** [comment]
cool man, no worries. glad to hear it's working!

**Comment by leifliddy** [comment]
make sure to do a ```git pull``` to update the repo. That was my bad, the updates directory exists by default on Fedora, but apparently not on Ubuntu systems. What was happening was the ```hci_uart.ko``` module was being copied to a file named ```updates```

**Comment by airyy** [comment]
Ah, the bytes itself not to the directory haha. No worries, and thanks for the continued support.
