### ISSUE TITLE
strlcpy error

### ISSUE THREAD

**Issue by amirian** [leifliddy/macbook12-bluetooth-driver#23]
Compiling is stopped in kernel v6.8 with this error message:
`/macbook12-audio-driver/build/hda/patch_cirrus_a1534_pcm.h:123:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
  123 |         strlcpy(str, chip_name, len);
      |         ^~~~~~~
      |         strscpy
`
I fixed it by replacing strlcpy with strscpy. However, if it is not recommended, please notify.

**Comment by leifliddy** [comment]
This project doesn't use strlcpy. Are you sure you're looking at the right project?

**Comment by amirian** [comment]
Sorry, I placed the issue in the wrong place. It is about the audio driver which has been corrected two weeks ago!
