### ISSUE TITLE
No Bluetooth on Macbook 12 2017 anymore

### ISSUE THREAD

**Issue by marcusenglert** [leifliddy/macbook12-bluetooth-driver#3]
Hi,
I have just run the new bluetooth driver sh on my 2017 macbook12. While a Bluetooth adapter was found by the system before it seems to be gone now. No Bluetooth anymore.
Thanks for your help
Best
Marcus

**Comment by leifliddy** [comment]
Which Linux distro/version are you running? 
Which kernel version?
Please post the output of ```uname -r```
If you're running kernel 5.0 or 5.1, please do a ```git pull``` and re-run ```install.bluetooth.sh```
I just updated this repo to support kernels 5.0 and 5.1

**Comment by marcusenglert** [comment]
Hi,
sorry for not being precise!
I am running Ubuntu 18.04 LTS most recent version
uname -r output: 5.0.0-37-generic
Trying to rerun the install now

Thanks

Marcus

**Comment by marcusenglert** [comment]
Hi,
works now! Many thanks!
Best
Marcus
