### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by linuxdevhub** [leifliddy/macbook12-bluetooth-driver#4]
I ended up with following screen.
Please give me hint how will i proceed?

![Screenshot from 2020-01-08 01-45-02](https://user-images.githubusercontent.com/58360140/71924221-c65dc900-31b8-11ea-93ee-27de897a6ef8.png)

**Comment by leifliddy** [comment]
Have you read the ```README.md``` file? 
Did you install the ```linux-headers-generic``` package?

**Comment by linuxdevhub** [comment]
yes, it seems headers are installed properly.
![Screenshot from 2020-01-08 12-59-12](https://user-images.githubusercontent.com/58360140/71957051-e1f7bc80-3216-11ea-9d58-a3e84f7d3fe0.png)

**Comment by leifliddy** [comment]
The first screen shot shows that you're running kernel ```5.3.14```. You need to have the ```linux-headers``` package installed for that version.

**Comment by linuxdevhub** [comment]
Thank you soo much for your support
