### ISSUE TITLE
unable to pair bluetooth devices

### ISSUE THREAD

**Issue by tristonwan** [leifliddy/macbook12-bluetooth-driver#6]
Hi, 
i am using Macbook 12 inch and installed with Ubuntu 20.04 LTS.
i have install the bluetooth driver and it is able to discover bluetooth devices. however it failed at pairing stage.
what should i do to fix it?

**Comment by leifliddy** [comment]
That sounds like a general Linux question, that likely isn't directly related to this project. 
I would run `bluetoothctl`  and list your devices with `devices`, then remove each of your devices with `remove` (just copy and paste the MAC address)
ie
```
[leif.liddy@black ~]$ bluetoothctl 
Agent registered
[bluetooth]# devices
Device 38:18:4C:24:B7:33 LE_WH-1000XM3
[bluetooth]# remove 38:18:4C:24:B7:33
[DEL] Device 38:18:4C:24:B7:33 LE_WH-1000XM3
Device has been removed
```
then try (re)-paring your device(s)
