### ISSUE TITLE
Trackpad and keyboard backlight stop working (Linux Mint 20)

### ISSUE THREAD

**Issue by FunkThatSheet** [leifliddy/macbook12-bluetooth-driver#8]
Trackpad and keyboard backlight stop working after the driver installation (while bluetooth starts working). Had to restore a btrfs backup to fix that.
OS: Linux Mint 20 Cinnamon
Kernel: 5.4.0-52-generic

I'm quite new to Linux so I'm not sure what information/logs/etc. could help.

**Comment by leifliddy** [comment]
You don't need to restore from a backup, just delete the custom module from:
```/lib/modules/$(uname -r)/updates/hci_uart.ko```
...then reboot your system (which is the easier method vs trying to reload all active bluetooth-related modules)

The system will then use the stock bluetooth module located at:
```/lib/modules/$(uname -r)/kernel/drivers/bluetooth/hci_uart.ko.xz``` 
**some distros don't compress the modules so, the name may just be ```hci_uart.ko```

If your keyboard wasn't working (when the system is booted), you could just boot to a previous kernel from the grub menu (the keyboard will always work pre-boot)
IIRC Mint hides the grub menu by default. It's that's the case, then I would definitely unhide the grub menu. 

However, the trackpad and keyboard lighting functions are provided by the ```applespi``` module and have absolutely nothing to do with the ```hci_uart``` module, so I highly doubt that's the cause of the issue. 

Did you try completely powering down your macbook vs rebooting it?

**Comment by FunkThatSheet** [comment]
Thanks for your answer. Yes, I've tried powering the macbook down that time, but I've noticed that this no backlight + trackpad issue happens sometimes even without this bt driver installed, shutting down and booting up again helps (probably, some Mint spi driver issue). So I've just installed the bt driver, powered the mac off and on twice and now it's working with bluetooth enabled. Cheers!
